/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 office.gltf --transform --types 
Files: office.gltf [34.78MB] > C:\Users\natha\Desktop\office-transformed.glb [1.14MB] (97%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh;
    Cube_2: THREE.Mesh;
    Cube_3: THREE.Mesh;
    Cube_4: THREE.Mesh;
    Cube_5: THREE.Mesh;
    Cube_6: THREE.Mesh;
    Cube_7: THREE.Mesh;
    Cube_8: THREE.Mesh;
    Cube_9: THREE.Mesh;
    Cube_10: THREE.Mesh;
    Cube_11: THREE.Mesh;
    Cube_12: THREE.Mesh;
    Cube_13: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    laminate_floor_02: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    PaletteMaterial005: THREE.MeshStandardMaterial;
    small_wooden_table_01: THREE.MeshStandardMaterial;
    steel_frame_shelves_02: THREE.MeshStandardMaterial;
    PottedPlant_04: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
  };
};

export function Office(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/office-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -0.294, 0]} scale={[0.13, 0.005, 0.06]}>
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube_4.geometry}
          material={materials.laminate_floor_02}
        />
        <mesh
          geometry={nodes.Cube_5.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          geometry={nodes.Cube_6.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cube_7.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Cube_8.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={nodes.Cube_9.geometry}
          material={materials.small_wooden_table_01}
        />
        <mesh
          geometry={nodes.Cube_10.geometry}
          material={materials.steel_frame_shelves_02}
        />
        <mesh
          geometry={nodes.Cube_11.geometry}
          material={materials.PottedPlant_04}
        />
        <mesh
          geometry={nodes.Cube_12.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Cube_13.geometry}
          material={materials.PaletteMaterial003}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/office-transformed.glb");
